name: Flutter CI/CD

on:
  push:
    branches: [master]

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter build apk --enable-experiment=non-nullable --no-sound-null-safety
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: android-build
          path: ./build/app/outputs/flutter-apk/app-release.apk